### ISSUE TITLE
RegEx pattern match not working with Retour field

### ISSUE THREAD

**Issue by green-plastic** [nystudio107/retour#30] opened 2016-07-26 21:04 UTC
Initially I noticed this when I was using FeedMe to import and having a default RegEx pattern to match.

My pattern was as follows: `\/editorial\/(.*)\/(.*)\/{slug}$`. This passes RegEx validation.

Only one row is ever inserted into `craft_retour_redirects` for that pattern. It really doesn't matter what the pattern is, only one row is ever inserted.

If I switch from RegEx to Exact Match, rows get inserted and redirects work fine.

I also tried to add in entries manually with the same issue.

**Comment by khalwat** [comment] 2016-08-05 20:55
I'm gonna get this worked out for you shortly, I just haven't had time to set up a test environment yet.

**Comment by green-plastic** [comment] 2016-08-05 20:56
No problem. Glad you're looking into it. Thanks!

**Comment by timkelty** [comment] 2016-08-29 15:31
I believe the problem is here: https://github.com/nystudio107/retour/blob/master/services/RetourService.php#L434-Lundefined

`$redirectsModel->redirectSrcUrl` is being compared instead of `$redirectsModel->redirectSrcUrlParsed`.

LIkely the same problem as #31

**Comment by khalwat** [comment] 2016-08-30 20:28
I checked in a fix to `develop`: 

https://github.com/nystudio107/retour/tree/develop

Sorry this took so long!

**Closed** 2016-08-30 20:37 UTC
