### ISSUE TITLE
Redirect Evaluation Order

### ISSUE THREAD

**Issue by parktool** [nystudio107/retour#56] opened 2017-01-27 23:34 UTC
I'm wondering if it would be possible to program Retour so that when it is comparing a URL with potential redirects, it loops through only Exact Matches before comparing to RegEx Matches.

The scenario that brought this to mind is this:
We recently redesigned our site and there are a number of old URLs that follow the pattern http://www.site.com/product/p/product-page-here-ab-1. Thankfully, most of the new URLs follow almost exactly the same pattern, http://www.site.com/product/product-page-here-ab-1, so it's just a matter of creating the RegEx match and capturing the slug.

Where I run into problems is when the old page URL is along the lines of http://www.site.com/product/p/product-page-here, but the new one changed for whatever reason (http://www.site.com/product/p/new-fancy-name-here-ab-1). If the RegEx redirect was added first, Retour (it seems) executes that redirect first, even though there is an exact redirect between the old and new link. That ends up redirecting to http://www.site.com/product/product-page-here, which still 404s.

The workaround I've found is to enter all the Exact Matches first, then enter the RegEx Match after so it is executed last. Since RegEx casts a wide net, it seems to make sense checking against Exact Matches first. Maybe there is a scenario I'm not thinking of where this wouldn't work. What do you think?

**Comment by khalwat** [comment] 2017-01-30 18:14
So currently the way it is implemented, no.

I think at some point, letting people change the order of the redirects would be a good thing, though.

**Comment by khalwat** [comment] 2017-02-10 19:06
This is really a duplicate of https://github.com/nystudio107/retour/issues/4

**Closed by khalwat** 2017-02-10 19:06 UTC
Labels: Feature Request

**Comment by kevinsmith** [comment] 2017-03-02 17:43
I +1 the OP because I agree that it would be nice to be able to explicitly declare rule priority, but I wanted to add this: the order in which redirects are currently evaluated is already problematic.

Retour gets its list of redirects to evaluate from `RetourService::getAllStaticRedirects()`, which orders them with the highest hit count first. (I'm assuming that's because that's how you want it ordered in the interface.) Because of this, redirect rules with higher hit counts are given higher priority. This seems like an especially flawed way of assigning priority because it's using an unexpected *and* ever-changing metric for determining priority.

So in the OP's case, even the work-around he assumes will work _may_ stop working at some point if later-created rules end up getting a higher hit count through some other means.

In keeping with the expected way the plugin works, I'd suggest ordering redirect rules by earliest creation date first.

**Comment by jakepm** [comment] 2020-07-22 15:05
Was this ever implemented? I have several complex regex rules for a site rebuild that needs to handle a vast array of potential URL formats and redirect based on some values in the captured string. However, multiple regex rules apply to some of the URLs in our input/test data and so it is essential that we be able to order the regex rules. Furthermore, explicit rules should always trigger before regex in my opinion, but ultimately we can settle with just specifying a manual order.

**Comment by khalwat** [comment] 2020-07-22 19:36
This has not been implemented; I haven't decided the best way to approach it.

**Comment by khalwat** [comment] 2020-07-22 19:37
@jakepm let's continue the discussion on this open ticket: https://github.com/nystudio107/craft-retour/issues/74
